version: '3'

services:
  app:
    build: .
    container_name: ng-cash-app
    ports:
      - "3003:3003"
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres
    container_name: ng-cash-db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ngcash
