//signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "username": "aaaaa",
    "password": "EricFelipe7"
}

###

//login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "username": "uuidteste",
    "password": "EricFelipe7"
}
