//signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "username": "efss7",
    "password": "Teste123"
}

###

//login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "username": "Eric",
    "password": "Teste123"
}

###
//viewBalance
GET http://localhost:3003/account/balance
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI0YTVkODc5NC02NWI1LTQxZWQtOTc1NS1jZjVmZGRkYTk2ZTYiLCJpYXQiOjE2Njg5Njg3MTgsImV4cCI6MTY2OTA1NTExOH0.N_3eMIgT_lbv0dTk-MeB09YiSxXLrILu_acLjPeATDA
###
//transfer
POST http://localhost:3003/transaction/transfer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI0YTVkODc5NC02NWI1LTQxZWQtOTc1NS1jZjVmZGRkYTk2ZTYiLCJpYXQiOjE2Njg5Njg3MTgsImV4cCI6MTY2OTA1NTExOH0.N_3eMIgT_lbv0dTk-MeB09YiSxXLrILu_acLjPeATDA
Content-Type: application/json

{
    "username": "Adeir",
    "value": 1
}
###
//viewCashIn
GET http://localhost:3003/transaction/cashIn
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI0YTVkODc5NC02NWI1LTQxZWQtOTc1NS1jZjVmZGRkYTk2ZTYiLCJpYXQiOjE2Njg5Njg3MTgsImV4cCI6MTY2OTA1NTExOH0.N_3eMIgT_lbv0dTk-MeB09YiSxXLrILu_acLjPeATDA
###
//viewCashOut
GET http://localhost:3003/transaction/cashOut
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI0YTVkODc5NC02NWI1LTQxZWQtOTc1NS1jZjVmZGRkYTk2ZTYiLCJpYXQiOjE2Njg5Njg3MTgsImV4cCI6MTY2OTA1NTExOH0.N_3eMIgT_lbv0dTk-MeB09YiSxXLrILu_acLjPeATDA
###
//viewByDate
POST  http://localhost:3003/transaction/byDate
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIyMmMzYzEwYi04ZmZjLTRmNDctODdiYS04NDFmNWNkMjVjM2IiLCJpYXQiOjE2Njg5Njg5MTEsImV4cCI6MTY2OTA1NTMxMX0.-NjL7qsk7NDUMVFzTRMDlfCVPhTXuVQDVMJ0C5zxxpY
Content-Type: application/json

{
    "date": "19/11/2022"
}