//signup
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "username": "Felipe",
    "password": "Teste123"
}

###

//login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "username": "teste2",
    "password": "Teste123"
}

###
//viewBalance
GET http://localhost:3003/account/balance
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIwODVmMGI5My1hZjE1LTQ5ZTgtYWIwNC0yZTlmZGVjYzJmYjIiLCJpYXQiOjE2Njg4NzE3NTMsImV4cCI6MTY2ODk1ODE1M30.B84hbOglcW_1JwjCATpr3LhmifjCLlYmMGdtvuqNpvw
###
//transfer
POST http://localhost:3003/transaction/transfer
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiIxNGExZDZkZS04YmEzLTRmMmYtYjczYS02MDM2MDM0MjI4YmEiLCJpYXQiOjE2Njg5MDEyODQsImV4cCI6MTY2ODk4NzY4NH0._sA8V4z9WtY1iu5xqoHInkssF0w9q6nbHRFXcOAU9WY
Content-Type: application/json

{
    "username": "teste2",
    "value": 1
}
###
//viewCashIn
GET http://localhost:3003/transaction/cashIn
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NzcwM2VkNC00NGEyLTQzOTMtYTU5ZC0yZjM1YjA4ODFlNmQiLCJpYXQiOjE2Njg5MDE5NDYsImV4cCI6MTY2ODk4ODM0Nn0.eCm5Ks7k6rxPFh66EEE3zd3LxuMLrXqeVP207B3ij7c

###
//viewCashOut
GET http://localhost:3003/transaction/cashOut
Authorization:  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2NvdW50SWQiOiI2NzcwM2VkNC00NGEyLTQzOTMtYTU5ZC0yZjM1YjA4ODFlNmQiLCJpYXQiOjE2Njg5MDE5NDYsImV4cCI6MTY2ODk4ODM0Nn0.eCm5Ks7k6rxPFh66EEE3zd3LxuMLrXqeVP207B3ij7c
